"""
The `BigInt` scalar type represents non-fractional signed whole numeric values.
"""
scalar BigInt

"""
A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar Date

"""An Ethereum address, validated and normalized to lowercase"""
scalar EthAddress

type Intent {
  amount: String
  createdAt: Date
  createdBlock: BigInt
  createdTxHash: String
  expiration: BigInt
  id: BigInt
  priceThreshold: String
  status: IntentStatus
  tokenFrom: EthAddress
  tokenTo: EthAddress
  updatedAt: Date
  updatedBlock: BigInt
  user: EthAddress
}

enum IntentStatus {
  ACTIVE
  CANCELLED
  EXECUTED
}

type Query {
  intentByCreatedTxHash(txHash: String!): Intent
  userIntents(limit: Int = 5, offset: Int = 0, status: IntentStatus, user: EthAddress!): [Intent!]
  userIntentsCount(status: IntentStatus, user: EthAddress!): Int
}