"""
The `BigInt` scalar type represents non-fractional signed whole numeric values.
"""
scalar BigInt

"""
A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar Date

"""An Ethereum address, validated and normalized to lowercase"""
scalar EthAddress

type Intent {
  amount: String
  createdAt: Date
  createdBlock: BigInt
  createdTxHash: String
  expiration: BigInt
  id: BigInt
  priceThreshold: String
  status: IntentStatus
  tokenFrom: EthAddress
  tokenTo: EthAddress
  updatedAt: Date
  updatedBlock: BigInt
  user: EthAddress
}

type IntentEvent {
  actor: String
  blockNumber: BigInt
  blockTimestamp: BigInt
  chainId: Int
  createdAt: Date
  eventType: IntentEventType
  id: BigInt
  intentId: BigInt
  logIndex: Int
  payload: JSON
  txHash: String
}

enum IntentEventType {
  CANCELLED
  CREATED
  EXECUTED
  UPDATED
}

enum IntentStatus {
  ACTIVE
  CANCELLED
  EXECUTED
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

type Query {
  intentEventByTxHash(chainId: Int, eventType: IntentEventType!, txHash: String!): IntentEvent
  intentEventsByIntentId(eventType: IntentEventType, intentId: BigInt!, limit: Int = 20, offset: Int = 0): [IntentEvent!]
  userIntents(fresh: Boolean = false, limit: Int = 5, offset: Int = 0, status: IntentStatus, user: EthAddress!): [Intent!]
  userIntentsCount(fresh: Boolean = false, status: IntentStatus, user: EthAddress!): Int
}