import type { Address } from "viem";

export const SEPOLIA_CONTRACT_ORACLE_ADDRESS = process.env
  .NEXT_PUBLIC_SEPOLIA_CONTRACT_ORACLE_ADDRESS as Address;
export const SEPOLIA_CONTRACT_SWAPPER_ADDRESS = process.env
  .NEXT_PUBLIC_SEPOLIA_CONTRACT_SWAPPER_ADDRESS as Address;
export const SEPOLIA_CONTRACT_INTENT_FACTORY_ADDRESS = process.env
  .NEXT_PUBLIC_SEPOLIA_CONTRACT_INTENT_FACTORY_ADDRESS as Address;
export const SEPOLIA_CONTRACT_INTENT_EXECUTOR_ADDRESS = process.env
  .NEXT_PUBLIC_SEPOLIA_CONTRACT_INTENT_EXECUTOR_ADDRESS as Address;

export const SEPOLIA_BTC_TOKEN_ADDRESS = process.env
  .NEXT_PUBLIC_SEPOLIA_BTC_TOKEN_ADDRESS as Address;
export const SEPOLIA_LINK_TOKEN_ADDRESS = process.env
  .NEXT_PUBLIC_SEPOLIA_LINK_TOKEN_ADDRESS as Address;
export const SEPOLIA_ETH_TOKEN_ADDRESS = process.env
  .NEXT_PUBLIC_SEPOLIA_ETH_TOKEN_ADDRESS as Address;
export const SEPOLIA_WRAPPED_ETH_TOKEN_ADDRESS = process.env
  .NEXT_PUBLIC_SEPOLIA_WRAPPED_ETH_TOKEN_ADDRESS as Address;

export const SEPOLIA_PRICE_FEED_CONTRACT_LINK_TO_ETH_ADDRESS = process.env
  .NEXT_PUBLIC_SEPOLIA_PRICE_FEED_CONTRACT_LINK_TO_ETH_ADDRESS as Address;
export const SEPOLIA_PRICE_FEED_CONTRACT_BTC_TO_ETH_ADDRESS = process.env
  .NEXT_PUBLIC_SEPOLIA_PRICE_FEED_CONTRACT_BTC_TO_ETH_ADDRESS as Address;
