packages:
  - apps/*
  - packages/*

catalog:
  '@cloudflare/workers-types': ^4.2
  '@types/node': 22.19.3
  dotenv: 17.3.1
  hono: ^4.11.6
  hono-rate-limiter: 0.5.3
  tsx: 4.21.0
  typescript: 5.9.3
  viem: 2.43.3
  wrangler: ^4.4.0
  zod: 4.3.6
